In [57]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, accuracy_score, confusion_matrix
from sklearn.tree import export_text
from sklearn.tree import export_graphviz

Fit a decision tree to predict the binary outcome `baby_low_weight` using `mom_weight`, `premature_labor`, `hypertension`, `irritability`
- Print and interpret the tree
- Does the model make good predictions of `baby_low_weight`?
- Include `smoked` and `race` to the model, is the new model better than the old one?

In [36]:
data=pd.read_excel('data/birth_weight.xlsx') #Hosmer & Lemeshow low birth weight data

In [37]:
data.columns=['id', 'baby_low_weight', 'mom_age', 'mom_weight', 'race', 'smoked', 'premature_labor', 'hypertension', 'irritability', 'doc_visit', 'baby_weight']

In [38]:
data.head()

id  baby_low_weight  mom_age  mom_weight   race     smoked  \
0  85                0       19         182  black  nonsmoker   
1  86                0       33         155  other  nonsmoker   
2  87                0       20         105  white     smoker   
3  88                0       21         108  white     smoker   
4  89                0       18         107  white     smoker   

   premature_labor  hypertension  irritability  doc_visit  baby_weight  
0                0             0             1          0         2523  
1                0             0             0          3         2551  
2                0             0             0          1         2557  
3                0             0             1          2         2594  
4                0             0             1          0         2600

In [94]:
X = data[['mom_weight', 'premature_labor', 'hypertension', 'irritability']]
y = data['baby_low_weight']

In [95]:
dtree = DecisionTreeClassifier()

In [96]:
train_test_split?

In [97]:
X_train, X_test, y_test, y_test = train_test_split(X, y, random_state=0, train_size=0.75)

In [98]:
X.shape

(189, 4)

In [99]:
X_train.shape

(141, 4)

In [100]:
y_train.shape

(141,)

In [101]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [102]:
#print(export_text(dtree, feature_names=list(X.columns)))

In [103]:
yfit_train = dtree.predict(X_train)

In [104]:
accuracy_score(y_train, yfit_train)

0.8936170212765957

In [105]:
confusion_matrix(y_train, yfit_train)

array([[95,  2],
       [13, 31]])

In [106]:
yfit_test = dtree.predict(X_test)

In [107]:
accuracy_score(y_test, yfit_test)

0.6458333333333334

In [108]:
confusion_matrix(y_test, yfit_test)

array([[28,  4],
       [13,  3]])

In [62]:
data2 = pd.get_dummies(data)
data2.head()

id  baby_low_weight  mom_age  mom_weight  premature_labor  hypertension  \
0  85                0       19         182                0             0   
1  86                0       33         155                0             0   
2  87                0       20         105                0             0   
3  88                0       21         108                0             0   
4  89                0       18         107                0             0   

   irritability  doc_visit  baby_weight  race_black  race_other  race_white  \
0             1          0         2523           1           0           0   
1             0          3         2551           0           1           0   
2             0          1         2557           0           0           1   
3             1          2         2594           0           0           1   
4             1          0         2600           0           0           1   

   smoked_nonsmoker  smoked_smoker  
0                 1              0  
1                 1              0  
2                 0              1  
3                 0              1  
4                 0              1

In [109]:
X = data2[['mom_weight', 'premature_labor', 'hypertension', 'irritability', 'race_black', 'race_other', 'smoked_smoker']]
y = data2['baby_low_weight']

In [110]:
X_train, X_test, y_test, y_test = train_test_split(X, y, random_state=0, train_size=0.75)

In [111]:
dtree = DecisionTreeClassifier()

In [112]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [113]:
yfit_test = dtree.predict(X_test)

In [114]:
accuracy_score(y_test, yfit_test)

0.5625

In [115]:
confusion_matrix(y_test, yfit_test)

array([[20, 12],
       [ 9,  7]])

In [120]:
dtree = DecisionTreeClassifier(max_features=4, max_leaf_nodes=10).fit(X_train, y_train)

In [121]:
yfit_test = dtree.predict(X_test)

In [122]:
accuracy_score(y_test, yfit_test)

0.6875

In [123]:
confusion_matrix(y_test, yfit_test)

array([[30,  2],
       [13,  3]])

In [124]:
print(export_text(dtree, feature_names=list(X.columns)))

|--- irritability <= 0.50
|   |--- mom_weight <= 107.50
|   |   |--- race_other <= 0.50
|   |   |   |--- class: 1
|   |   |--- race_other >  0.50
|   |   |   |--- mom_weight <= 105.50
|   |   |   |   |--- class: 0
|   |   |   |--- mom_weight >  105.50
|   |   |   |   |--- class: 1
|   |--- mom_weight >  107.50
|   |   |--- smoked_smoker <= 0.50
|   |   |   |--- mom_weight <= 118.50
|   |   |   |   |--- class: 0
|   |   |   |--- mom_weight >  118.50
|   |   |   |   |--- mom_weight <= 120.50
|   |   |   |   |   |--- class: 1
|   |   |   |   |--- mom_weight >  120.50
|   |   |   |   |   |--- class: 0
|   |   |--- smoked_smoker >  0.50
|   |   |   |--- mom_weight <= 131.50
|   |   |   |   |--- class: 0
|   |   |   |--- mom_weight >  131.50
|   |   |   |   |--- hypertension <= 0.50
|   |   |   |   |   |--- class: 0
|   |   |   |   |--- hypertension >  0.50
|   |   |   |   |   |--- class: 0
|--- irritability >  0.50
|   |--- class: 0

